### ISSUE TITLE
Add spectator option when player loses all hearts

### ISSUE THREAD

**Issue by tyepavitt** [dewPrzemuS/P-LifeSteal#5]
Add option in config so that when player loses all hearts they go into spectator mode (invisible and invulnerable). Also would be cool to add in the config whether to receive a spectator Item, and what slot it will be so players can choose players on the worlds (if add multiverse support) or server!   Also would be great to add permission for admins to not be on the spectator list and make it so players who are vanished won't be on the list either.

**Comment by dewPrzemuS** [comment]
I don't think many people will use this. Such an feature will be possible using custom commands when losing all hearts/reviving, with use of [Skript](https://github.com/SkriptLang/Skript) or maybe even commands from vanilla Minecraft.

**Comment by LadyHaley** [comment]
Not to necro a dead thread but I am looking for a lifesteal plugin that does this. I am looking for a hardcore style life steal plugin, the hardcore style plugins with no life steal do it, but they go into spectator after any death, or after a set amount of lives are lost, and dont work great with additional life steal plugins on top of it
